{% set name = "jom" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/{{ name }}/{{ name }}_{{ version.replace('.', '_') }}.zip
  sha256: 89405212add992c35783fc5e938b2d7252d8447fde1dc64d335714325b54d668

build:
  number: 0
  skip: true  # [not win]
  script:
    - copy *.bat %LIBRARY_BIN%\
    - copy *.exe %LIBRARY_BIN%\
    - copy *.xml %LIBRARY_BIN%\

test:
  commands:
    - jom /VERSION

about:
  home: https://wiki.qt.io/Jom
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: 'jom is a clone of nmake to support the execution of multiple independent commands in parallel'
  description: 'jom is a clone of nmake to support the execution of multiple independent commands in parallel'
  dev_url: https://github.com/qt-labs/jom
  doc_url: https://wiki.qt.io/Jom

extra:
  recipe-maintainers:
    - isuruf
