{% set name = "jom" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/{{ name }}/{{ name }}_{{ version.replace('.', '_') }}.zip
  sha256: 4c8af345586a9a08fbfd2f613fcac748226d91a75627aa3581b297dd513046fe

build:
  number: 0
  skip: true  # [not win]
  script:
    - copy *.bat %LIBRARY_BIN%\
    - copy *.exe %LIBRARY_BIN%\
    - copy *.xml %LIBRARY_BIN%\

test:
  commands:
    - jom /VERSION

about:
  home: https://wiki.qt.io/Jom
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: jom is a clone of nmake to support the execution of multiple independent commands in parallel
  description: jom is a clone of nmake to support the execution of multiple independent commands in parallel
  dev_url: https://github.com/qt-labs/jom
  doc_url: https://wiki.qt.io/Jom

extra:
  recipe-maintainers:
    - isuruf
