travis:
  secure:
    BINSTAR_TOKEN: fvG+zcoCvSBf0CUwnw4ElNnx75/xwmWfqYnfcxn2mSFDLGjol4SnRgGjEeHUKEPW0InCn4jv3KiUriccmoQ0qhlCkzltAWN8lA4Q8V2pwu2h27YKxZt/D6x+WAGGl28cAxNIBtAlibp1uyePQz6c4I1DiHFvjplwSF927/X5w1qBdvZfSJW+vPYpzCq6LLjVXm4WPHida/XwWDlTk3AjZH0psnYS/uYbc76C8v/yvRtEbNTJbJTN3sLStehTsf4W7livf3Qyurgglc9jon5AOrwbCP8kXxt0a1Id5ouBa1lXIiaVdN/85Am1qiaqlVSSGYWJFxu3mOHkkWGarT6hHGJFLcv9h4KX20ENUF8Zi19kljiy81gpEuPHPNVPk4nf46K2aKru7eeG2L28PAUCoeaElB5z9KA/aVeS8VwqieXfjhlY7Vc4c1p6f2afT/CsZUxCXBNV2jNdD4tT3qTj7zWUuye41WFS4yd94O7iDv8dh/Hm9vBwjv5bfPUaeA/wLCw9cPLUm28ioF9uyzNNZcuLOsKY2BgYnhY24tFEeDa6UzXX9suzSM8llQKn5cyoPespofj2ME8sRL8YSdEkdIa1qPeqmFm8z+f1YuGnyn1yP+KcnihKYazn/1avIZsYsJe3ZXpF1PAb52WHynccs4/yXOrxa+05vdNc1qyYEjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
