travis:
  secure:
    BINSTAR_TOKEN: g/rbTT5bvmIzmFvcX7BRjmvFuMd13i/NT8Kc3TLJnU2bPZ9JmUN5htwbCoGbB3tEI/AouTmCGlvRT7kVVt578s9hAOkLNDNytCSoZepTR/zx/hvRyZAezYz7WZEA7nyhZSQa0wU1Y8rIA3utJT+Dt6SDU7qmYe1qOXgIEL8M+S1FYUa2bsXCFWp9ri3klM/Gv3JXLTz11PIJoHKDPASt7FYT8HvmfBsbiAWaYq9o1mnOaotQ9kol3WECAwDNmIweLo6NCM3nu6YJwJnYSIssTVSlvYBHET+b5QmutSU1bJLPyDQkBxU17HHniGCMekRT0u5A2b/sWhRgA3I9U0YIDM39xXIWNZAZ+4dFQY8hN1cOiPa43z3dAWiibR0zv03tHYNFd2VW29faUxpbKS96NHwZNxnKonDRE2pF6RqHyDdxi5mt2Zi1wEF0/zpkSxPFUfuEYzR5V+f8afRa9i2UNWofM+is0722b9lLHTm2cVNDQUJfexmx0+LYeqoYxZIL7k1BGzbIpNX0KkA4jPC7GuiILw2tt3dPSrb3hBZlBmx/XJeQfZiBEE3iteVaThmCFLWU4hk4/JQsHxV1rvsHYcgVhwmD848oVFDNvAx2em6FpFzzh37bslG3j7cehZspx3oIBas8QdE5yukSQpCFlRYPt1S1Q0yQsZ3ENf3BqdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
